# PostgreSQL
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>

development:
  <<: *default
  database: od_listings_ruby_development
  pool: 5

test:
  <<: *default
  database: od_listings_ruby_test
  pool: 5

production:
  <<: *default
  database: od_listings_ruby_production
  pool: 25
